name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  UV_VERSION: 0.11.15
  UV_LOCKED: 1
  UV_NO_SYNC: 1
  PY_COLORS: 1
  CARGO_TERM_COLOR: always

jobs:
  rust-ci:
    runs-on: "${{ matrix.platform }}-latest"
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu", "macos", "windows"]
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9  # v1.94.1
      with:
        toolchain: 1.94.1
        components: clippy
    - name: cargo clippy
      run: cargo clippy --verbose
    - name: cargo test
      run: cargo test --verbose
  python-ci:
    runs-on: "${{ matrix.platform }}-latest"
    strategy:
      fail-fast: false
      # https://blog.jaraco.com/efficient-use-of-ci-resources/
      matrix:
        python: ["3.10", "3.14"]
        platform: ["ubuntu", "macos", "windows"]
        include:
        - python: "3.11"
          platform: "ubuntu"
        - python: "3.12"
          platform: "ubuntu"
        - python: "3.13"
          platform: "ubuntu"
    env:
      UV_PYTHON: ${{ matrix.python }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - name: Setup uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
      with:
        version: ${{ env.UV_VERSION }}
    - name: Environment
      id: sync
      run: uv sync --extra cli
    - name: taplo (TOML formatting)
      if: ${{ !cancelled() && steps.sync.conclusion == 'success' && matrix.platform == 'ubuntu' }}
      run: uv run taplo fmt --check --diff pyproject.toml Cargo.toml rustfmt.toml
    - name: ruff format
      if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
      run: uv run ruff format --diff
    - name: ruff lint
      if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
      run: uv run ruff check --output-format github
    - name: pytest
      if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
      run: uv run pytest -vv
    - name: pyright
      if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
      run: uv run pyright src tests
